name: DEPLOYMENT

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: /Users/fanzru/backend/BE-SISFO-KLINIK/scripts
    steps:
      - uses: actions/checkout@v2
      - name: Preparing to deploy to production 🚀🤘
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            sudo su
            cd ~/backend/BE-SISFO-KLINIK/scripts
            chmod +x deploy.sh
            ./deploy.sh