name: DEPLOYMENT

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: /Users/fanzru/backend/BE-SISFO-KLINIK/scripts
    steps:
      - uses: actions/checkout@v2
      - name: Preparing to deploy to production 🚀🤘
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            sudo su
            cd /home/fanzru/backend/BE-SISFO-KLINIK/
            git fetch origin development
            git reset --hard origin/development
            source /home/fanzru/.profile
            go mod tidy
            pm2 restart deploy.json
           